name: Abhishek Naik
title: Abhishek Naik's Website

include: ['_pages', 'uploads']

base_url: "/website/"

social:
  twitter: anaik96
  email: abhisheknaik22296@gmail.com
  goodreads: 41821528-abhishek-naik
  github: abhisheknaik96
  google_scholar: 9gV4DRsAAAAJ

markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge
